services:
  next-app:
    container_name: pru-next
    build:
      context: ./pru-next
      dockerfile: dev.Dockerfile

    env_file:
      - .env
    volumes:
      - ./pru-next/src:/app/src
      - ./pru-next/public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    driver: bridge
